### ISSUE TITLE
iPhone 12 真机运行闪退

### ISSUE THREAD

**Issue by kevinxuxi** [wangdengwu/flutter_in_action_source_code#1]

**Comment by wangdengwu** [comment]
模拟器可以运行么？
真机的话，首先debug模式不能脱离编辑器独立打开，如果需要独立打开，需要使用--release模式打包到真机上。
具体如果使用的是Android studio的话，
![image](https://user-images.githubusercontent.com/1317704/131219498-53256f1c-258f-464e-b05d-827bff9c8715.png)
![image](https://user-images.githubusercontent.com/1317704/131219508-bbb4861d-24a5-4123-ad8a-d472202a51ef.png)
![image](https://user-images.githubusercontent.com/1317704/131219529-943c8dd7-8192-43f1-bdc0-5b0aa483ac6b.png)

**Comment by wangdengwu** [comment]
已解决
